---
report_description: 'These dealers are not sending Roadster their website traffic
  - please contact them to make sure the Roadster GA tags are implemented on their
  site.  Without website traffic, many of the key Roadster metrics are going to be
  0 or ugly N/As.  This list excludes customers who have ''opted out''.  If your customer
  wants to opt out, please send a slack message to #anlytx_L2_Support.'
is_full_width: false
hide_run_button: false
