---
report_description: This is a list of all our dealer partners and the Net Promoter
  score they get from their car buyers.  This answers the question - which DPIDs have
  the highest net promoter scores?
is_full_width: false
hide_run_button: false
